import type { Metadata } from "next";

import "../styles/globals.css";


import Profile from "@/components/profile";

export const metadata: Metadata = {
  title: "Bryan's Portfolio",
  description: "Generated by create next app",
};
import {
  poppins,
  inter,
  fira_sans,
  roboto_mono,
  oswald,
  montserrat,
} from "./fonts";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${inter.variable} ${poppins.variable} ${fira_sans.variable} ${roboto_mono.variable} ${oswald.variable} ${montserrat.variable}`}
    >
      <body className={inter.className}>
        {/* <Header /> */}

          <div className="flex bg-black text-white">
            {/* <SideNav /> */}
            <div className="flex  py-10 h-screen  flex-col space-y-2 px-10 w-96">
              <Profile />
            </div>
            <div className="w-full overflow-x-auto">
              <div className="overflow-auto ">
                <div className="w-full flex justify-center mx-auto  overflow-auto overflow-y-auto ">
                  <div className="w-full ">{children}</div>
                </div>
              </div>
            </div>
          </div>
      
      </body>
    </html>
  );
}
